# Generated by Django 4.2.6 on 2024-02-23 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_budgetlabels_budgetlabel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='year',
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.DateField(),
        ),
    ]
