# Generated by Django 4.2.6 on 2024-02-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_month_year_alter_month_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
