# Generated by Django 4.2.6 on 2024-02-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_budget_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetlabel',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
