# Generated by Django 4.2.6 on 2024-02-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_budgetlabel_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='planned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
