# Generated by Django 4.2.6 on 2024-02-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_budgetcategory_planned_budgetcategory_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='incoming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='outgoing',
            field=models.BooleanField(default=False),
        ),
    ]
