# Generated by Django 4.2.6 on 2024-02-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_transaction_incoming_transaction_outgoing'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_name',
            field=models.CharField(default='Name', max_length=100),
            preserve_default=False,
        ),
    ]
