# Generated by Django 4.2.6 on 2024-03-06 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0008_transaction_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='name',
            field=models.CharField(default='Month Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='budget.month'),
        ),
    ]
