# Generated by Django 4.2.6 on 2024-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='planned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budgetcategory',
            name='received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
