# Generated by Django 4.2.6 on 2024-03-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_alter_budgetlabel_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='deleted_status',
            field=models.BooleanField(default=False),
        ),
    ]
