# Generated by Django 4.1.7 on 2024-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_budgetlabel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='original_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
